const testQuestionsData = [
    { text: "Nenne die drei Gehörknöchelchen im Mittelohr.", answers: ["Hammer (Malleus)", "Amboss (Incus)", "Steigbügel (Stapes)"], categoryNames: ["Skelett"] },
    { text: "Welche Abschnitte hat der Dünndarm?", answers: ["Zwölffingerdarm (Duodenum)", "Leerdarm (Jejunum)", "Krummdarm (Ileum)"], categoryNames: ["Organe"] },
    { text: "Welche sind die vier Haupt-Blutgruppen im AB0-System?", answers: ["A", "B", "AB", "0"], categoryNames: ["Organe"] },
    { text: "Nenne die drei Schichten der menschlichen Haut.", answers: ["Oberhaut (Epidermis)", "Lederhaut (Dermis)", "Unterhaut (Subkutis)"], categoryNames: ["Organe"] },
    { text: "Welche Knochen bilden das Kniegelenk?", answers: ["Oberschenkelknochen (Femur)", "Schienbein (Tibia)", "Kniescheibe (Patella)"], categoryNames: ["Skelett"] },
    { text: "Nenne die vier Kammern des menschlichen Herzens.", answers: ["Rechter Vorhof", "Rechte Kammer", "Linker Vorhof", "Linke Kammer"], categoryNames: ["Organe"] },
    { text: "Welche Hormone werden in der Bauchspeicheldrüse produziert?", answers: ["Insulin", "Glukagon", "Somatostatin"], categoryNames: ["Organe"] },
    { text: "Nenne die drei Abschnitte der Wirbelsäule (ohne Kreuz-/Steißbein).", answers: ["Halswirbelsäule", "Brustwirbelsäule", "Lendenwirbelsäule"], categoryNames: ["Skelett"] },
    { text: "Welche Aufgaben hat das Blut im Körper?", answers: ["Sauerstofftransport", "Nährstofftransport", "Abwehr von Krankheitserregern", "Wärmeregulierung", "Blutgerinnung"], categoryNames: ["Organe"] },
    { text: "Nenne die fünf Sinne des Menschen.", answers: ["Sehen", "Hören", "Riechen", "Schmecken", "Tasten"], categoryNames: ["Nervensystem"] },
    { text: "Aus welchen zwei Hauptteilen besteht das Nervensystem?", answers: ["Zentrales Nervensystem (ZNS)", "Peripheres Nervensystem (PNS)"], categoryNames: ["Nervensystem"] },
    { text: "Welche Knochen gehören zum Schultergürtel?", answers: ["Schlüsselbein (Clavicula)", "Schulterblatt (Scapula)"], categoryNames: ["Skelett"] },
    { text: "Nenne die drei Arten von Blutgefäßen.", answers: ["Arterien", "Venen", "Kapillaren"], categoryNames: ["Organe"] },
    { text: "Welche Organe gehören zum Harnsystem?", answers: ["Nieren", "Harnleiter", "Harnblase", "Harnröhre"], categoryNames: ["Organe"] },
    { text: "Nenne die drei großen Speicheldrüsen im Mundbereich.", answers: ["Ohrspeicheldrüse", "Unterkieferspeicheldrüse", "Unterzungendrüse"], categoryNames: ["Organe"] },
    { text: "Welche sind die drei Haupttypen von Muskelgewebe?", answers: ["Skelettmuskulatur", "Herzmuskulatur", "Glatte Muskulatur"], categoryNames: ["Muskeln"] },
    { text: "Nenne die Bestandteile des Blutes.", answers: ["Blutplasma", "Rote Blutkörperchen (Erythrozyten)", "Weiße Blutkörperchen (Leukozyten)", "Blutplättchen (Thrombozyten)"], categoryNames: ["Organe"] },
    { text: "Welche Knochen bilden den Unterarm?", answers: ["Speiche (Radius)", "Elle (Ulna)"], categoryNames: ["Skelett"] },
    { text: "Nenne die drei Gehirnabschnitte.", answers: ["Großhirn", "Kleinhirn", "Stammhirn"], categoryNames: ["Nervensystem"] },
    { text: "Welche Vitamine sind fettlöslich?", answers: ["Vitamin A", "Vitamin D", "Vitamin E", "Vitamin K"], categoryNames: ["Organe"] },
    { text: "Wie viele Wirbel hat die Halswirbelsäule?", answers: ["7"], categoryNames: ["Skelett"] },
    { text: "Welches ist der größte Muskel im Körper?", answers: ["Musculus gluteus maximus"], categoryNames: ["Muskeln"] },
    { text: "In welchem Organ wird Galle produziert?", answers: ["Leber"], categoryNames: ["Organe"] },
    { text: "Was ist das größte Organ des Menschen?", answers: ["Haut"], categoryNames: ["Organe"] },
    { text: "Wie viele Liter Blut hat ein Erwachsener durchschnittlich?", answers: ["5-6 Liter"], categoryNames: ["Organe"] },
    { text: "Nenne die Fachbegriffe für Einatmen und Ausatmen.", answers: ["Inspiration", "Exspiration"], categoryNames: ["Organe"] },
    { text: "Welche Klappen befinden sich im Herzen?", answers: ["Mitralklappe", "Trikuspidalklappe", "Aortenklappe", "Pulmonalklappe"], categoryNames: ["Organe"] },
    { text: "Welche Knochen bilden den Unterschenkel?", answers: ["Schienbein (Tibia)", "Wadenbein (Fibula)"], categoryNames: ["Skelett"] },
    { text: "Nenne die drei Schichten der Herzwand.", answers: ["Endokard", "Myokard", "Epikard"], categoryNames: ["Organe"] },
    { text: "Welche Funktion hat das Kleinhirn?", answers: ["Koordination von Bewegungen", "Gleichgewicht"], categoryNames: ["Nervensystem"] },
    { text: "Welche Zellorganellen werden als 'Kraftwerke der Zelle' bezeichnet?", answers: ["Mitochondrien"], categoryNames: ["Organe"] },
    { text: "Welche zwei Gase werden bei der Atmung ausgetauscht?", answers: ["Sauerstoff (O2)", "Kohlendioxid (CO2)"], categoryNames: ["Organe"] },
    { text: "Nenne die Bestandteile eines Neurons.", answers: ["Zellkörper (Soma)", "Dendriten", "Axon"], categoryNames: ["Nervensystem"] },
    { text: "Welche zwei Knochen bilden den Beckengürtel?", answers: ["Hüftbein", "Kreuzbein"], categoryNames: ["Skelett"] },
    { text: "Welche Aufgaben hat das Skelett?", answers: ["Stützfunktion", "Schutz der Organe", "Bewegung", "Blutbildung", "Mineralspeicher"], categoryNames: ["Skelett"] },
    { text: "Nenne die drei Phasen der Wundheilung.", answers: ["Exsudationsphase", "Proliferationsphase", "Regenerationsphase"], categoryNames: ["Organe"] },
    { text: "Welche Drüse reguliert den Stoffwechsel durch Thyroxin?", answers: ["Schilddrüse"], categoryNames: ["Organe"] },
    { text: "Nenne die vier Geschmacksrichtungen (klassisch).", answers: ["Süß", "Sauer", "Salzig", "Bitter"], categoryNames: ["Organe"] },
    { text: "Welches Hormon wird bei Stress im Nebennierenmark ausgeschüttet?", answers: ["Adrenalin"], categoryNames: ["Organe"] },
    { text: "Wie heißt die kleinste funktionelle Einheit der Niere?", answers: ["Nephron"], categoryNames: ["Organe"] },
    { text: "Welche Strukturen gehören zum äußeren Ohr?", answers: ["Ohrmuschel", "Gehörgang", "Trommelfell (Grenze)"], categoryNames: ["Organe"] },
    { text: "Nenne die drei Hauptaufgaben des Dickdarms.", answers: ["Eindickung des Stuhls", "Wasser-Rückresorption", "Elektrolyt-Aufnahme"], categoryNames: ["Organe"] },
    { text: "Welche Muskeln bilden den Oberschenkel (vorne)?", answers: ["Musculus quadriceps femoris"], categoryNames: ["Muskeln"] },
    { text: "Nenne die Bestandteile des Schädels.", answers: ["Gehirnschädel", "Gesichtsschädel"], categoryNames: ["Skelett"] },
    { text: "Welche Zellen sind für die Immunabwehr zuständig?", answers: ["Leukozyten (Weiße Blutkörperchen)"], categoryNames: ["Organe"] },
    { text: "Welche Gelenkarten gibt es im menschlichen Körper?", answers: ["Kugelgelenk", "Scharniergelenk", "Drehgelenk", "Sattelgelenk", "Eigelenk"], categoryNames: ["Skelett"] },
    { text: "Nenne die Funktionen der Niere.", answers: ["Ausscheidung von Abfallstoffen", "Regulation des Wasserhaushalts", "Blutdruckregulation", "Säure-Basen-Haushalt"], categoryNames: ["Organe"] },
    { text: "Welche Sehnenplatte verbindet die Wadenmuskeln mit der Ferse?", answers: ["Achillessehne"], categoryNames: ["Muskeln"] },
    { text: "Nenne die drei Abschnitte des Kehlkopfes.", answers: ["Supraglottis", "Glottis", "Subglottis"], categoryNames: ["Organe"] },
    { text: "Welche Aufgabe hat das Myelin im Nervensystem?", answers: ["Elektrische Isolation", "Beschleunigung der Reizleitung"], categoryNames: ["Nervensystem"] },
    { text: "Nenne die vier Lungenlappen (insgesamt).", answers: ["3 rechts", "2 links"], categoryNames: ["Organe"] },
    { text: "Welche Knochen bilden den Brustkorb?", answers: ["Brustbein (Sternum)", "Rippen", "Brustwirbelsäule"], categoryNames: ["Skelett"] },
    { text: "Was ist die Funktion der Gallenblase?", answers: ["Speicherung von Galle", "Eindickung von Galle"], categoryNames: ["Organe"] },
    { text: "Nenne die Schichten der Augapfelwand.", answers: ["Lederhaut / Hornhaut", "Aderhaut / Iris", "Netzhaut"], categoryNames: ["Nervensystem"] },
    { text: "Welches Protein transportiert Sauerstoff?", answers: ["Hämoglobin"], categoryNames: ["Organe"] },
    { text: "Nenne die drei Hirnhäute.", answers: ["Dura mater", "Arachnoidea", "Pia mater"], categoryNames: ["Nervensystem"] },
    { text: "Welche Muskeln gehören zur Bauchmuskulatur?", answers: ["Gerader Bauchmuskel", "Äußerer schräger Bauchmuskel", "Innerer schräger Bauchmuskel", "Querer Bauchmuskel"], categoryNames: ["Muskeln"] },
    { text: "Nenne die Aufgaben des Magens.", answers: ["Speicherung von Nahrung", "Durchmischung", "Beginn der Eiweißverdauung", "Abtöten von Bakterien (Magensäure)"], categoryNames: ["Organe"] },
    { text: "Welche Knochen bilden den Handwurzelbereich?", answers: ["Kahnbein", "Mondbein", "Dreiecksbein", "Erbsenbein", "Großes Vieleckbein", "Kleines Vieleckbein", "Kopfbein", "Hakenbein"], categoryNames: ["Skelett"] },
    { text: "Wie viele Rippenpaare hat ein Mensch normalerweise?", answers: ["12"], categoryNames: ["Skelett"] },
    { text: "Nenne die Funktionen der Milz.", answers: ["Abbau alter Erythrozyten", "Immunabwehr", "Speicherung von Thrombozyten"], categoryNames: ["Organe"] },
    { text: "Welche Substanzen befinden sich im Magensaft?", answers: ["Salzsäure", "Pepsinogen / Pepsin", "Schleim", "Intrinsic Factor"], categoryNames: ["Organe"] },
    { text: "Nenne die zwei Typen von Fotorezeptoren im Auge.", answers: ["Stäbchen (Hell/Dunkel)", "Zapfen (Farben)"], categoryNames: ["Nervensystem"] },
    { text: "Welche Hormone produziert die Nebennierenrinde?", answers: ["Aldosteron", "Cortisol", "Androgene"], categoryNames: ["Organe"] },
    { text: "Nenne die Aufgaben des Lymphsystems.", answers: ["Flüssigkeitstransport", "Immunabwehr", "Fetttransport"], categoryNames: ["Organe"] },
    { text: "Welche Knochen bilden das Becken?", answers: ["Darmbein", "Sitzbein", "Schambein", "Kreuzbein"], categoryNames: ["Skelett"] },
    { text: "Nenne die drei Abschnitte des Pharynx (Rachen).", answers: ["Nasopharynx", "Oropharynx", "Laryngopharynx"], categoryNames: ["Organe"] },
    { text: "Welche Aufgabe hat das Zwerchfell?", answers: ["Wichtigster Atemmuskel"], categoryNames: ["Muskeln"] },
    { text: "Nenne die Bestandteile des passiven Bewegungsapparates.", answers: ["Knochen", "Gelenke", "Bänder"], categoryNames: ["Skelett"] },
    { text: "Welche Bestandteile hat der Zahnhalteapparat?", answers: ["Wurzelzement", "Zahnfleisch", "Zahnfach", "Wurzelhaut"], categoryNames: ["Skelett"] },
    { text: "Welche Funktionen hat die Haut?", answers: ["Schutzfunktion", "Sinnesorgan", "Temperaturregulation", "Stoffwechselfunktion"], categoryNames: ["Organe"] },
    { text: "Nenne die Abschnitte des Dickdarms.", answers: ["Blinddarm mit Appendix", "Grimmdarm (Colon)", "Mastdarm (Rektum)"], categoryNames: ["Organe"] },
    { text: "Welche Aufgabe haben die Venenklappen?", answers: ["Verhinderung des Rückflusses von Blut"], categoryNames: ["Organe"] },
    { text: "Nenne die Schichten des Herzbeutels.", answers: ["Perikard", "Epikard (viszerales Blatt)"], categoryNames: ["Organe"] },
    { text: "Welche Knochen gehören zum Unterarm?", answers: ["Radius", "Ulna"], categoryNames: ["Skelett"] },
    { text: "Nenne die Hormone der Schilddrüse.", answers: ["T3 (Trijodthyronin)", "T4 (Thyroxin)", "Calcitonin"], categoryNames: ["Organe"] },
    { text: "Welche Aufgaben hat die Nasenhöhle?", answers: ["Erwärmung der Luft", "Befeuchtung der Luft", "Reinigung der Luft", "Riechfunktion"], categoryNames: ["Organe"] },
    { text: "Nenne die drei Anteile des Hüftbeins.", answers: ["Os ilium", "Os ischii", "Os pubis"], categoryNames: ["Skelett"] },
    { text: "Welche Aufgaben hat das Fruchtwasser?", answers: ["Schutz vor Stößen", "Bewegungsfreiheit", "Temperaturkonstanz"], categoryNames: ["Organe"] },
    { text: "Nenne die Knochen des Fußes.", answers: ["Fußwurzelknochen", "Mittelfußknochen", "Zehenknochen"], categoryNames: ["Skelett"] },
    { text: "Welche Funktion hat die Aorta?", answers: ["Hauptschlagader des Körperkreislaufs"], categoryNames: ["Organe"] },
    { text: "Nenne die vier Grundgewebearten.", answers: ["Epithelgewebe", "Binde- und Stützgewebe", "Muskelgewebe", "Nervengewebe"], categoryNames: ["Organe"] },
    { text: "Welche Knochen bilden das Ellenbogengelenk?", answers: ["Humerus", "Radius", "Ulna"], categoryNames: ["Skelett"] },
    { text: "Nenne die Aufgaben des Speichels.", answers: ["Anfeuchten der Nahrung", "Beginn der Kohlenhydratverdauung", "Schutz der Mundschleimhaut"], categoryNames: ["Organe"] },
    { text: "Welche Strukturen bilden den Kehlkopf?", answers: ["Schildknorpel", "Ringknorpel", "Stellknorpel", "Kehldeckel"], categoryNames: ["Organe"] },
    { text: "Nenne die Hormone des Hypophysenhinterlappens.", answers: ["Oxytocin", "ADH (Antidiuretisches Hormon)"], categoryNames: ["Organe"] },
    { text: "Welche Knochen gehören zum Gesichtsschädel?", answers: ["Oberkiefer", "Unterkiefer", "Jochbein", "Nasenbein"], categoryNames: ["Skelett"] },
    { text: "Nenne die drei Phasen des Schluckaktes.", answers: ["Orale Phase", "Pharyngeale Phase", "Ösophageale Phase"], categoryNames: ["Organe"] },
    { text: "Welche Aufgaben hat der Knorpel?", answers: ["Druckelastizität", "Reibungsminderung im Gelenk"], categoryNames: ["Skelett"] },
    { text: "Nenne die Bestandteile des Spermas.", answers: ["Spermien", "Sekret der Prostata", "Sekret der Bläschendrüsen", "Sekret der Cowper-Drüsen"], categoryNames: ["Organe"] },
    { text: "Welche Knochen bilden das Schultergelenk?", answers: ["Humerus (Oberarm)", "Scapula (Schulterblatt)"], categoryNames: ["Skelett"] },
    { text: "Nenne die Schichten der Gebärmutter.", answers: ["Endometrium", "Myometrium", "Perimetrium"], categoryNames: ["Organe"] },
    { text: "Welche Aufgaben hat das Bindegewebe?", answers: ["Verbindung von Organen", "Stützfunktion", "Speicherfunktion", "Abwehrfunktion"], categoryNames: ["Organe"] },
    { text: "Nenne die drei Abschnitte des Stammskeletts.", answers: ["Schädel", "Wirbelsäule", "Brustkorb"], categoryNames: ["Skelett"] },
    { text: "Welche Hormone werden im Eierstock gebildet?", answers: ["Östrogen", "Progesteron"], categoryNames: ["Organe"] },
    { text: "Nenne die Bestandteile der Tränenflüssigkeit.", answers: ["Wasser", "Salze", "Proteine (Lysozym)"], categoryNames: ["Organe"] },
    { text: "Welche Knochen bilden den Hirnschädel?", answers: ["Stirnbein", "Scheitelbein", "Schläfenbein", "Hinterhauptsbein", "Keilbein", "Siebbein"], categoryNames: ["Skelett"] },
    { text: "Nenne die Aufgaben des Testosterons.", answers: ["Spermienbildung", "Ausbildung männlicher Geschlechtsmerkmale", "Anaboler Effekt"], categoryNames: ["Organe"] },
    { text: "Welche Strukturen gehören zum Innenohr?", answers: ["Hörschnecke (Cochlea)", "Bogengänge (Gleichgewichtsorgan)"], categoryNames: ["Organe"] },
    { text: "Nenne die drei Schichten der Arterienwand.", answers: ["Tunica interna", "Tunica media", "Tunica externa"], categoryNames: ["Organe"] }
];
